### ISSUE TITLE
Berkeley Function Leaderboard for OpenFunctionsv2 Error Handling Error

### ISSUE THREAD

**Issue by sachit-menon** [ShishirPatil/gorilla#231]
When running `python openfunctions_evaluation.py --model gorilla-openfunctions-v2 --test_category all --temperature 0.3` I get:

```
retrieve_holiday_by_year(year='2018', country='US'), retrieve_holiday_by_year(year='2020', country='DE'), retrieve_holiday_by_year(year='2019', country='ES'), retrieve_holiday_by_year(year='2021', country='GB')
 78%|█████████████████████████████████████████████████████████████████████████████▏                     | 39/50 [02:38<00:44,  4.07s/it]
Traceback (most recent call last):
  File "/proj/vondrick4/sachit/miniconda3/envs/misc/lib/python3.10/site-packages/openai/api_requestor.py", line 403, in handle_error_response
    error_data = resp["error"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/proj/vondrick2/sachit/projects2/gorilla/berkeley-function-leaderboard/openfunctions_evaluation.py", line 445, in <module>
    result = call_to_model(
  File "/proj/vondrick2/sachit/projects2/gorilla/berkeley-function-leaderboard/openfunctions_evaluation.py", line 258, in call_to_model
    completion = openai.ChatCompletion.create(
  File "/proj/vondrick4/sachit/miniconda3/envs/misc/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/proj/vondrick4/sachit/miniconda3/envs/misc/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/proj/vondrick4/sachit/miniconda3/envs/misc/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/proj/vondrick4/sachit/miniconda3/envs/misc/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/proj/vondrick4/sachit/miniconda3/envs/misc/lib/python3.10/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
  File "/proj/vondrick4/sachit/miniconda3/envs/misc/lib/python3.10/site-packages/openai/api_requestor.py", line 405, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: 'Internal Server Error' (HTTP response code was 500)
```

Why is it calling the OpenAI API in the first place when evaluating the openfunctions-v2 model?

**Comment by ShishirPatil** [comment]
Hey @sachit-menon we only make our end-point open-ai chat-completion API compatible so it can be a drop-in replacement. Do you mind trying it out again, the server seems to be healthy from our end.
