### ISSUE TITLE
[bug] OpenFunctions-v2: <Issue>

### ISSUE THREAD

**Issue by shraddhasun** [ShishirPatil/gorilla#466]
**Describe the bug**

This is the error I'm seeing when I try to run inference_hosted.py.
Error communicating with OpenAI: HTTPConnectionPool(host='luigi.millennium.berkeley.edu', port=8000)

**Is that host down?**
If not, how do I access that endpoint?

**Screenshots**

This is the stacktrace

``` 
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/gorilla/openfunctions/inference_hosted.py", line 52, in <module>
    run_conversation()
  File "/root/gorilla/openfunctions/inference_hosted.py", line 39, in run_conversation
    completion = openai.ChatCompletion.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 289, in request
    result = self.request_raw(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 619, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='luigi.millennium.berkeley.edu', port=8000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd776bd6dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Proposed Solution**
If you want to suggest a proposed solution or an idea for one? 

**Additional context**
Add any other context about the problem here.

**Comment by ShishirPatil** [comment]
Thanks for raising this @shraddhasun This should now be fixed?
