### ISSUE TITLE
When [Evaluate the Response with AST tree matching]: TypeError: __init__() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by Peter-Hamster** [ShishirPatil/gorilla#469]
When execute the sample code in "Evaluate the Response with AST tree matching":
https://github.com/ShishirPatil/gorilla/tree/main/eval

python ast_eval_th.py --api_dataset ../../data/api/torchhub_api.jsonl --apibench ../../data/apibench/torchhub_eval.json --llm_responses ../eval-data/responses/torchhub/response_torchhub_Gorilla_FT_0_shot.jsonl
 
 
Traceback (most recent call last):
  File "D:\yyyyy\evaluation\gorilla\eval\eval-scripts\ast_eval_th.py", line 203, in <module>
    main(args)
  File "D:\yyyyy\evaluation\gorilla\eval\eval-scripts\ast_eval_th.py", line 162, in main
    api_database, qa_pairs, llm_responses, ast_database = parse_dataset(args)
                                                          ^^^^^^^^^^^^^^^^^^^
  File "D:\yyyyy\evaluation\gorilla\eval\eval-scripts\ast_eval_th.py", line 112, in parse_dataset
    for ast_tree in ast_trees:
  File "C:\Users\xxxx\miniconda3\Lib\concurrent\futures\_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\miniconda3\Lib\concurrent\futures\_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\miniconda3\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\miniconda3\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\xxxx\miniconda3\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\yyyyy\evaluation\gorilla\eval\eval-scripts\ast_eval_th.py", line 45, in ast_parse
    LANGUAGE = Language("codebleu/parser/my-languages.so", lang)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: __init__() takes exactly 1 argument (2 given)
    
    
   Can anyone help me with this issue? Seems like passing extra argument?  Thanks for your time

**Comment by Hanci1999** [comment]
It could be due to the latest version of the tree-sitter package, consider downgrading to version 0.20.4
