### ISSUE TITLE
The Urban Dictionary from the RapidAPI is not serving, can't evaluate execution data

### ISSUE THREAD

**Issue by zhangyingerjelly** [ShishirPatil/gorilla#563]
The Urban Dictionary from the RapidAPI is not serving, can't evaluate execution data.

**Comment by CharlieJCJ** [comment]
Hi @zhangyingerjelly, thanks for raising. I just checked Urban Dictionary API on my end. It looks fine to me? Can you share the error message you're facing?

Source: https://rapidapi.com/community/api/urban-dictionary
```bash
❯ python                                                          
Python 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get(url="https://mashape-community-urban-dictionary.p.rapidapi.com/define", headers={"X-RapidAPI-Key": REPLACE_THIS_WITH_YOUR_KEY, "X-RapidAPI-Host": "mashape-community-urban-dictionary.p.rapidapi.com"}, params={"term": "artwash"}).json()
{'list': [{'definition': 'Buying [art] for museums or galleries in order to improve public [opinion] of you, [your family], or your company.', 'permalink': 'http://artwash.urbanup.com/13751556', 'thumbs_up': 450, 'author': 'Briansue', 'word': 'artwash', 'defid': 13751556, 'current_vote': '', 'written_on': '2019-03-27T12:41:12.095Z', 'example': "The [sackler family] couldn't even artwash away their part in [the north] american opioid [crisis].", 'thumbs_down': 182}]}
```

**Comment by BeerTai** [comment]
I have the same problem
```
(BFCL) [myname@node17 eval_checker]$ python eval_runner.py --model THUDM/glm-4-9b-chat --test-category python
<posix.ScandirIterator object at 0x7f79dfeaf9f0>
UniGPT2-08-02-00-20240730 ['THUDM_glm-4-9b-chat']
THUDM_glm-4-9b-chat ['THUDM_glm-4-9b-chat']
🦍 Model: THUDM_glm-4-9b-chat
🔍 Running test: relevance
✅ Test completed: relevance. 🎯 Accuracy: 0.875
🔍 Running test: simple
✅ Test completed: simple. 🎯 Accuracy: 0.8675
🔍 Running test: executable_multiple_function
---- Getting real-time execution result from ground truth for executable_multiple_function ----
Getting Executable Expected Output:  26%|█████████████████████████████████▎                                                                                              | 13/50 [02:10<06:10, 10.00s/it]
Traceback (most recent call last):
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f79dfa791b0>: Failed to establish a new connection: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.urbandictionary.com', port=443): Max retries exceeded with url: /v0/define?term=lit (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f79dfa791b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fl/nlp/myname/gorilla-main/berkeley-function-call-leaderboard/eval_checker/eval_runner.py", line 472, in <module>
    runner(model_names, test_categories, api_sanity_check)
  File "/fl/nlp/myname/gorilla-main/berkeley-function-call-leaderboard/eval_checker/eval_runner.py", line 366, in runner
    get_executable_expected_output(prompt_file)
  File "/fl/nlp/myname/gorilla-main/berkeley-function-call-leaderboard/eval_checker/eval_runner_helper.py", line 766, in get_executable_expected_output
    exec(
  File "<string>", line 2, in <module>
  File "/fl/nlp/myname/gorilla-main/berkeley-function-call-leaderboard/eval_checker/executable_python_function.py", line 418, in find_term_on_urban_dictionary
    response = requests.get(url, headers=headers, params=querystring)
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/sessions.py", line 724, in send
    history = [resp for resp in gen]
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/sessions.py", line 724, in <listcomp>
    history = [resp for resp in gen]
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/sessions.py", line 265, in resolve_redirects
    resp = self.send(
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.urbandictionary.com', port=443): Max retries exceeded with url: /v0/define?term=lit (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f79dfa791b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

**Comment by chenhengzh** [comment]
I also encountered this problem. Have you resolved it?

**Comment by LiaoNiuyu** [comment]
> I get the same error
> 
> ```
> (BFCL) [myname@node17 eval_checker]$ python eval_runner.py --model THUDM/glm-4-9b-chat --test-category python
> 🦍 Model: THUDM_glm-4-9b-chat
> 🔍 Running test: relevance
> ✅ Test completed: relevance. 🎯 Accuracy: 0.875
> 🔍 Running test: simple
> ✅ Test completed: simple. 🎯 Accuracy: 0.8675
> 🔍 Running test: executable_multiple_function
> ---- Getting real-time execution result from ground truth for executable_multiple_function ----
> Getting Executable Expected Output:  26%|█████████████████████████████████▎                                                                                              | 13/50 [02:10<06:10, 10.00s/it]
> Traceback (most recent call last):
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/connection.py", line 196, in _new_conn
>     sock = connection.create_connection(
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
>     raise err
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
>     sock.connect(sa)
> OSError: [Errno 101] Network is unreachable
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
>     response = self._make_request(
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
>     raise new_e
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
>     self._validate_conn(conn)
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
>     conn.connect()
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/connection.py", line 615, in connect
>     self.sock = sock = self._new_conn()
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/connection.py", line 211, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f79dfa791b0>: Failed to establish a new connection: [Errno 101] Network is unreachable
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
>     resp = conn.urlopen(
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
>     retries = retries.increment(
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
>     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.urbandictionary.com', port=443): Max retries exceeded with url: /v0/define?term=lit (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f79dfa791b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/fl/nlp/myname/gorilla-main/berkeley-function-call-leaderboard/eval_checker/eval_runner.py", line 472, in <module>
>     runner(model_names, test_categories, api_sanity_check)
>   File "/fl/nlp/myname/gorilla-main/berkeley-function-call-leaderboard/eval_checker/eval_runner.py", line 366, in runner
>     get_executable_expected_output(prompt_file)
>   File "/fl/nlp/myname/gorilla-main/berkeley-function-call-leaderboard/eval_checker/eval_runner_helper.py", line 766, in get_executable_expected_output
>     exec(
>   File "<string>", line 2, in <module>
>   File "/fl/nlp/myname/gorilla-main/berkeley-function-call-leaderboard/eval_checker/executable_python_function.py", line 418, in find_term_on_urban_dictionary
>     response = requests.get(url, headers=headers, params=querystring)
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/api.py", line 73, in get
>     return request("get", url, params=params, **kwargs)
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/api.py", line 59, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/sessions.py", line 724, in send
>     history = [resp for resp in gen]
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/sessions.py", line 724, in <listcomp>
>     history = [resp for resp in gen]
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/sessions.py", line 265, in resolve_redirects
>     resp = self.send(
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/myname/anaconda3/envs/BFCL/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.urbandictionary.com', port=443): Max retries exceeded with url: /v0/define?term=lit (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f79dfa791b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
> ```
> 
> however，in [https://rapidapi.com/community/api/urban-dictionary/playground](url)，we can get the response: ![image](https://private-user-images.githubusercontent.com/29746659/356178056-a9d1e145-f4e2-48b6-8e30-a67b3b820247.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5ODI1OTgsIm5iZiI6MTczNTk4MjI5OCwicGF0aCI6Ii8yOTc0NjY1OS8zNTYxNzgwNTYtYTlkMWUxNDUtZjRlMi00OGI2LThlMzAtYTY3YjNiODIwMjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDA5MTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMmYzYjkwYjQxNjZiOTBkMDAyMzQ5MDg1NGIwYmJjZDc5ZDdjMDMxZGRmZDcyMGQwMmI0YjhhMjMwMWI1NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L9W_GLBaLMIdr5kj17mcY3EVn4sIiRxxX56Fw3fVd-I) ![image](https://private-user-images.githubusercontent.com/29746659/356178481-dbe4678e-93ee-4d4e-bedf-78b83f28d4c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5ODI1OTgsIm5iZiI6MTczNTk4MjI5OCwicGF0aCI6Ii8yOTc0NjY1OS8zNTYxNzg0ODEtZGJlNDY3OGUtOTNlZS00ZDRlLWJlZGYtNzhiODNmMjhkNGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDA5MTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMmUyNzhmMGJhODQ4YjY3OWU5ZTljMzFkMjllMTgzOGEyODU1NzE0ODZlZjJjMDY1NmVmMzAyNzk3OGZhYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ioen6yvREH5utWxWqdHQv257WsKRr54T4DHUxR9MGcM)

I also encountered the same problem. Have you solved it?

**Comment by LiaoNiuyu** [comment]
> I also encountered this problem. Have you resolved it?
Have you solved this problem yet?

**Comment by sghyan16** [comment]
same problem here

**Comment by TarferSoul** [comment]
the same issue

**Comment by GuudMan** [comment]
same problem here, how to solve it?

**Comment by Leejunlin28** [comment]
same problem here, how to solve it?

**Comment by TarferSoul** [comment]
I guess the issue is caused by IP location. When I use a machine at China Mainland, I encounter the same issue. After trying another machine at Singapore, the issue does not appear. Maybe you can try some network proxy, I think it will work!
