### ISSUE TITLE
[BFCL] proprietary model handle

### ISSUE THREAD

**Issue by BeerTai** [ShishirPatil/gorilla#651]
**Describe the issue**
The Privatized Model Deployment
When I copied yi.py to implement my proprietary model handle, I got errors:
```
Traceback (most recent call last):
  File "/gorilla/berkeley-function-call-leaderboard/openfunctions_evaluation.py", line 124, in multi_threaded_inference
    result, metadata = handler.inference(copy.deepcopy(test_case), include_debugging_log)
  File "/gorilla/berkeley-function-call-leaderboard/bfcl/model_handler/base_handler.py", line 41, in inference
    return self.inference_single_turn_FC(test_entry, include_debugging_log)
  File "/gorilla/berkeley-function-call-leaderboard/bfcl/model_handler/base_handler.py", line 415, in inference_single_turn_FC
    inference_data: dict = self._pre_query_processing_FC(test_entry)
TypeError: myHandler._pre_query_processing_FC() missing 1 required positional argument: 'test_entry'

```

**ID datapoint**
1. Datapoint / Model Handler permalink: 
2. Issue: 
2. Gorilla repo commit #: 

**What is the issue**

**Proposed Changes**

{
 'previous_datapoint':[], 
 'updated_datapoint':[]
}

**Additional context**

**Comment by HuanzhiMao** [comment]
Hi @BeerTai,

Thanks for pointing this out. I will raise a quick patch for it.
